"""Fireworks-backed kernel edit policy.

Uses Fireworks' OpenAI-compatible chat completions endpoint:
https://api.fireworks.ai/inference/v1/chat/completions
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from typing import Any

from protean.model.harness import harness_for_kernel_edit
from protean.model.policy import CandidateEdit

DEFAULT_FIREWORKS_MODEL = "accounts/fireworks/models/gpt-oss-120b"
DEFAULT_FIREWORKS_BASE_URL = "https://api.fireworks.ai/inference/v1"


def _extract_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = re.sub(r"^```(?:json)?\s*", "", stripped)
        stripped = re.sub(r"\s*```$", "", stripped)
    match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
    if not match:
        raise ValueError("Fireworks response did not contain a JSON object")
    return json.loads(match.group(0))


def _validate_source(source: str) -> None:
    if "def solution(" not in source:
        raise ValueError("Fireworks edit did not define solution(...)")
    if "@triton.jit" not in source:
        raise ValueError("Fireworks edit did not include @triton.jit")


def build_kernel_edit_prompt(*, op: str, current_best: str, best_summary: dict) -> str:
    return f"""You are Protean's GPU-kernel optimization coding agent.

Improve the current best Triton kernel for op `{op}`.

Return ONLY JSON:
{{
  "name": "short_snake_case_edit_name",
  "reason": "why this edit should improve speed or robustness",
  "source": "full Python source defining a @triton.jit kernel and solution(...)"
}}

Rules:
- preserve correctness before speed
- use a real @triton.jit kernel
- do not call PyTorch to do the kernel work
- do not hardcode train or held-out shapes
- keep the public solution(...) signature unchanged for the op

Current verifier summary:
{json.dumps(best_summary, sort_keys=True)}

Current best source:
```python
{current_best}
```
"""


def call_fireworks_chat(
    prompt: str,
    *,
    model: str = DEFAULT_FIREWORKS_MODEL,
    base_url: str = DEFAULT_FIREWORKS_BASE_URL,
    api_key: str | None = None,
    max_tokens: int = 4096,
    temperature: float = 0.2,
) -> tuple[str, dict[str, int]]:
    key = api_key or os.environ.get("FIREWORKS_API_KEY")
    if not key:
        raise RuntimeError("FIREWORKS_API_KEY is required for Fireworks-backed edits")

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You return strict JSON and no extra prose."},
            {"role": "user", "content": prompt},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    req = urllib.request.Request(
        f"{base_url.rstrip('/')}/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Fireworks request failed: HTTP {exc.code}: {body}") from exc

    content = data["choices"][0]["message"]["content"]
    usage = data.get("usage", {})
    return content, {
        "prompt_tokens": int(usage.get("prompt_tokens", 0) or 0),
        "completion_tokens": int(usage.get("completion_tokens", 0) or 0),
        "total_tokens": int(usage.get("total_tokens", 0) or 0),
    }


def fireworks_kernel_edit(
    *,
    op: str,
    current_best: str,
    best_summary: dict,
    model: str = DEFAULT_FIREWORKS_MODEL,
    base_url: str = DEFAULT_FIREWORKS_BASE_URL,
) -> CandidateEdit:
    prompt = build_kernel_edit_prompt(op=op, current_best=current_best, best_summary=best_summary)
    text, usage = call_fireworks_chat(prompt, model=model, base_url=base_url)
    payload = _extract_json(text)
    source = str(payload["source"])
    _validate_source(source)
    return CandidateEdit(
        name=str(payload.get("name") or "fireworks_edit"),
        reason=str(payload.get("reason") or f"Generated by {model}."),
        source=source,
        harness=harness_for_kernel_edit(),
        policy="fireworks",
        tokens=usage["total_tokens"],
    )
